
<a href="https://www.zero-grad.com/">
         <img alt="Zero Grad" src="https://i.postimg.cc/7hJWBrFs/pythondataanalysis.png" >
      </a>

# Data Description

You can get data from WHO : https://data.who.int/dashboards/covid19/data

| Field name | Type | Description |
| --- | --- | --- |
| Date_reported | Date | Date of reporting to WHO |
| Country_code | String | ISO Alpha-2 country code |
| Country | String | Country, territory, area |
| WHO_region | String | WHO regional offices: WHO Member States are grouped into six WHO regions -- Regional Office for Africa (AFRO), Regional Office for the Americas (AMRO), Regional Office for South-East Asia (SEARO), Regional Office for Europe (EURO), Regional Office for the Eastern Mediterranean (EMRO), and Regional Office for the Western Pacific (WPRO). |
| New_cases | Integer | New confirmed cases. Calculated by subtracting previous cumulative case count from current cumulative cases count.* |
| Cumulative_cases | Integer | Cumulative confirmed cases reported to WHO to date. |
| New_deaths | Integer | New confirmed deaths. Calculated by subtracting previous cumulative deaths from current cumulative deaths.* |
| Cumulative_deaths | Integer | Cumulative confirmed deaths reported to WHO to date. |

# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import plotly.express as px

# Exploring the Data

In [2]:
df = pd.read_csv('https://srhdpeuwpubsa.blob.core.windows.net/whdh/COVID/WHO-COVID-19-global-daily-data.csv')
df.head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-04,AI,Anguilla,AMR,NaN,0,NaN,0
1,2020-01-04,AZ,Azerbaijan,EUR,NaN,0,NaN,0
2,2020-01-04,BD,Bangladesh,SEAR,0.0,0,0.0,0
3,2020-01-04,BB,Barbados,AMR,NaN,0,NaN,0
4,2020-01-04,BR,Brazil,AMR,NaN,0,NaN,0

In [4]:
df.fillna(0, inplace=True)

In [5]:
df.columns = df.columns.str.lower()

In [6]:
df['date_reported'] = pd.to_datetime(df['date_reported'], format='%Y-%m-%d')

In [7]:
df['year'] = df.date_reported.dt.year
df['month'] = df.date_reported.dt.month

In [8]:
df.head()

,date_reported,country_code,country,who_region,new_cases,cumulative_cases,new_deaths,cumulative_deaths,year,month
0,2020-01-04,AI,Anguilla,AMR,0.0,0,0.0,0,2020,1
1,2020-01-04,AZ,Azerbaijan,EUR,0.0,0,0.0,0,2020,1
2,2020-01-04,BD,Bangladesh,SEAR,0.0,0,0.0,0,2020,1
3,2020-01-04,BB,Barbados,AMR,0.0,0,0.0,0,2020,1
4,2020-01-04,BR,Brazil,AMR,0.0,0,0.0,0,2020,1

# Tasks

In [9]:
# Task 1: Create a new column called 'season' that specify {'Winter', 'Spring', 'Summer', 'Autumn'}

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Autumn'

df['season'] = df['month'].apply(get_season)

In [10]:
df.sample(5)

,date_reported,country_code,country,who_region,new_cases,cumulative_cases,new_deaths,cumulative_deaths,year,month,season
294782,2023-05-16,AG,Antigua and Barbuda,AMR,0.0,9106,0.0,146,2023,5,Spring
307278,2023-07-07,NO,Norway,EUR,0.0,1485883,0.0,5592,2023,7,Summer
43044,2020-07-01,TK,Tokelau,WPR,0.0,0,0.0,0,2020,7,Summer
406716,2024-08-24,PN,Pitcairn,WPR,0.0,4,0.0,0,2024,8,Summer
484144,2025-07-13,MA,Morocco,EMR,0.0,1279115,0.0,16305,2025,7,Summer

In [11]:
# Task 2: Filter by 'season': Find Total Deaths and Total new cases per season. Visualize it

df.groupby('season')[['new_cases', 'new_deaths']].sum()

          new_cases  new_deaths
season
Autumn  125197322.0   1522853.0
Spring  163771192.0   1836025.0
Summer  143516860.0   1594253.0
Winter  345988843.0   2146585.0

In [12]:
data = df.groupby('season')[['new_cases', 'new_deaths']].sum()

px.bar(data, x=data.index, y='new_cases', title=' Total new cases per season')

In [13]:
px.bar(data, x=data.index, y='new_deaths', title=' Total new deaths per season')

In [14]:
# Task 3: Filter by 'region' and 'season' : Find Total Deaths and Total new cases per season. Visualize it

df.groupby(['who_region', 'season'])[['new_cases', 'new_deaths']].sum()

                     new_cases  new_deaths
who_region season
AFR        Autumn    1206625.0     27371.0
           Spring    1339375.0     20843.0
           Summer    3440044.0     71845.0
           Winter    3602810.0     55473.0
AMR        Autumn   32874167.0    581854.0
           Spring   32039656.0    798689.0
           Summer   45617101.0    781410.0
           Winter   83071241.0    898244.0
EMR        Autumn    4558566.0     97027.0
           Spring    4957448.0     80949.0
           Summer    7143056.0    107538.0
           Winter    6758841.0     66461.0
EUR        Autumn   56235711.0    573658.0
           Spring   63427310.0    624587.0
           Summer   41039760.0    235661.0
           Winter  120619500.0    847092.0
OTHER      Autumn          0.0         0.0
           Spring         61.0         7.0
           Summer          0.0         0.0
           Winter        703.0         6.0
SEAR       Autumn    9763754.0    135584.0
           Spring   20550994.0    208633.0
           Summer   12900232.0    227064.0
           Winter   11886202.0     75975.0
WPR        Autumn   20558499.0    107359.0
           Spring   41456348.0    102317.0
           Summer   33376667.0    170735.0
           Winter  120049546.0    203334.0

In [16]:
for region in df['who_region'].unique():
    data = df[df['who_region'] == region].groupby('season')[['new_cases', 'new_deaths']].sum()
    fig = px.bar(data, x=data.index, y='new_cases', title=' Total new cases per season in ' + region)
    fig.show()

In [17]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

def seasons_per_region(region):
    data = df[df['who_region'] == region].groupby('season')[['new_cases', 'new_deaths']].sum()
    # subplots
    fig = make_subplots(rows=1, cols=2, subplot_titles=('Total new cases per season', 'Total new deaths per season'))
    fig.add_trace(go.Bar(x=data.index, y=data['new_cases']), row=1, col=1)
    fig.add_trace(go.Bar(x=data.index, y=data['new_deaths']), row=1, col=2)
    fig.update_layout(title_text=f'Total new cases and deaths per season in {region}')
    fig.show()

In [18]:
for region in df['who_region'].unique():
    seasons_per_region(region)